#!/bin/sh

dashm=$1
message=$2

gitstatus="$(git status)"
nothingword="nothing to commit, working directory clean"

#echo "Hi ( $gitstatus )"
#if echo "${gitstatus}" | grep --quiet --line-regexp --fixed-strings "${gitword}"; then
#    echo yes
#else
#    echo no
#fi

if $(echo "$gitstatus" | fgrep -wq -e "nothing to commit, working directory clean") ; then 
    echo yes
else
    echo no
fi

# Find which is your current branch
if currentBranch=$(git symbolic-ref --short -q HEAD)
then
    echo On $dashm branch "$currentBranch"
    echo "Pulling updates from the remote branch ( $message ) ..."
else
    echo ERROR: Cannot find the current branch!
fi
